// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rckxdcgtiuzysvszluhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJja3hkY2d0aXV6eXN2c3psdWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTE3NTQsImV4cCI6MjA2MjA2Nzc1NH0.KyyYc6J1CnPSxPdQKKPYR_1d-eaqLCGr4hqWgt4hEjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);